env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: off
  import/extensions:
    - off # Отключаем требование расширений для ESM
  no-trailing-spaces: error
  eol-last: error