env:
  node: true       # Поддержка Node.js
  es2021: true     # Современный ECMAScript
  jest: true       # Поддержка Jest
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest  # Последняя версия ECMAScript
  sourceType: module   # Поддержка ESM (import/export)
rules:
  no-console: off
  import/extensions:
    - off          # Отключаем требование расширений для ESM
  no-trailing-spaces: error
  eol-last: error
  no-restricted-syntax: off  # Разрешаем for...of (если нужно)